---
name: torrust
services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /var/lib/torrust/proxy/webroot:/var/www/html
      - /var/lib/torrust/certbot/etc:/etc/letsencrypt
      - /var/lib/torrust/certbot/lib:/var/lib/letsencrypt
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - proxy

  proxy:
    image: nginx:mainline-alpine
    container_name: proxy
    restart: unless-stopped
    networks:
      - backend_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/lib/torrust/proxy/webroot:/var/www/html
      - /var/lib/torrust/proxy/etc/nginx-conf:/etc/nginx/conf.d
      - /var/lib/torrust/proxy/certs:/etc/ssl/certs
      - /var/lib/torrust/proxy/private:/etc/ssl/private
      - /var/lib/torrust/certbot/etc:/etc/letsencrypt
      - /var/lib/torrust/certbot/webroot:/var/lib/torrust/certbot/webroot
      - /var/lib/torrust/certbot/lib:/var/lib/letsencrypt
      - /var/lib/torrust/dhparam:/etc/ssl/dhparam
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - tracker
      - grafana

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
    networks:
      - backend_network
    ports:
      - "3100:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v3.0.1
    container_name: prometheus
    tty: true
    restart: unless-stopped
    networks:
      - backend_network
    ports:
      - "9090:9090"  # This port should not be exposed to the internet
    volumes:
      - /var/lib/torrust/prometheus/etc:/etc/prometheus:Z
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - tracker

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - backend_network
    ports:
      - "3306:3306"  # Only for debugging, remove in production
    volumes:
      - mysql_data:/var/lib/mysql
      - /var/lib/torrust/mysql/init:/docker-entrypoint-initdb.d:ro
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost",
             "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  tracker:
    image: torrust/tracker:develop
    container_name: tracker
    tty: true
    restart: unless-stopped
    environment:
      - USER_ID=${USER_ID:-1000}
      # Database connection for tracker (using Figment override pattern)
      - TORRUST_TRACKER_CONFIG_OVERRIDE_CORE__DATABASE__DRIVER=mysql
      - TORRUST_TRACKER_CONFIG_OVERRIDE_CORE__DATABASE__PATH=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
      # Admin API token for tracker (using Figment override pattern)
      - TORRUST_TRACKER_CONFIG_OVERRIDE_HTTP_API__ACCESS_TOKENS__ADMIN=${TRACKER_ADMIN_TOKEN}
    networks:
      - backend_network
    ports:
      - 6868:6868/udp
      - 6969:6969/udp
      - 7070:7070
      - 1212:1212
    volumes:
      - /var/lib/torrust/tracker/lib:/var/lib/torrust/tracker:Z
      - /var/lib/torrust/tracker/log:/var/log/torrust/tracker:Z
      - /var/lib/torrust/tracker/etc:/etc/torrust/tracker:Z
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - mysql

networks:
  backend_network: {}

volumes:
  mysql_data: {}
  grafana_data: {}
