# Generated Docker Compose environment file for ${ENVIRONMENT}
# Generated on: ${GENERATION_DATE}

# Database Configuration
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
MYSQL_DATABASE=${MYSQL_DATABASE}
MYSQL_USER=${MYSQL_USER}
MYSQL_PASSWORD=${MYSQL_PASSWORD}

# Tracker Configuration
USER_ID=${USER_ID}
TORRUST_TRACKER_DATABASE=${TORRUST_TRACKER_DATABASE}
TORRUST_TRACKER_DATABASE_URL=${TORRUST_TRACKER_DATABASE_URL}

# Grafana Configuration
GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
