{
 "title": "Torrust Live Demo Tracker (metrics)",
 "description": "Using metric endpoint:\n\nhttps://tracker.torrust-demo.com/api/v1/metrics?token=MyAccessToken&format=prometheus",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Completed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tracker_core_persistent_torrents_downloads_total{job=\"tracker_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Torrents",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "swarm_coordination_registry_torrents_total{job=\"tracker_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Seeders",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "swarm_coordination_registry_peer_connections_total{job=\"tracker_metrics\", peer_role=\"seeder\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leechers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "swarm_coordination_registry_peer_connections_total{job=\"tracker_metrics\", peer_role=\"leecher\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP4 Connections (per sec)",
   "type": "timeseries",
   "description": "Request per second in 15 minutes",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(udp_tracker_server_requests_accepted_total{job=\"tracker_metrics\", request_kind=\"connect\", server_binding_address_ip_family=\"inet\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP4 Announces (per sec)",
   "type": "timeseries",
   "description": "Request per second in 15 minutes",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(udp_tracker_server_requests_accepted_total{job=\"tracker_metrics\", request_kind=\"announce\", server_binding_address_ip_family=\"inet\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP4 Scrapes (per sec)",
   "type": "timeseries",
   "description": "Request per second in 15 minutes",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(udp_tracker_server_requests_accepted_total{job=\"tracker_metrics\", request_kind=\"scrape\", server_binding_address_ip_family=\"inet\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP4 Errors (per sec)",
   "type": "timeseries",
   "description": "Request per second in 15 minutes",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(udp_tracker_server_errors_total{job=\"tracker_metrics\", server_binding_address_ip_family=\"inet\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP4 Average Connect Time",
   "type": "timeseries",
   "description": "UDP4 Average Connect Processing Time",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg(udp_tracker_server_performance_avg_processing_time_ns{job=\"tracker_metrics\", request_kind=\"connect\", server_binding_address_ip_family=\"inet\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP4 Average Announce Time",
   "type": "timeseries",
   "description": "UDP4 Average Announce Processing Time",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg(udp_tracker_server_performance_avg_processing_time_ns{job=\"tracker_metrics\", request_kind=\"announce\", server_binding_address_ip_family=\"inet\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP4 Average Scrape Time",
   "type": "timeseries",
   "description": "UDP4 Average Scrape Processing Time",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg(udp_tracker_server_performance_avg_processing_time_ns{job=\"tracker_metrics\", request_kind=\"scrape\", server_binding_address_ip_family=\"inet\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP4 Banned Requests (per sec)",
   "type": "timeseries",
   "description": "UDP4 Banned Requests (per sec)",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(udp_tracker_server_requests_banned_total{job=\"tracker_metrics\", server_binding_address_ip_family=\"inet\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP4 Requests and Responses (per sec)",
   "type": "timeseries",
   "description": "UDP 4 requests and responses",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(udp_tracker_server_requests_received_total{job=\"tracker_metrics\", server_binding_address_ip_family=\"inet\"}[15m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(udp_tracker_server_responses_sent_total{job=\"tracker_metrics\", server_binding_address_ip_family=\"inet\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP Banned IPs",
   "type": "timeseries",
   "description": "UDP Banned IPs",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
   "targets": [
    {
     "expr": "sum(udp_tracker_server_ips_banned_total{job=\"tracker_metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP4 aborted requests (per second)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(udp_tracker_server_requests_aborted_total{job=\"tracker_metrics\", server_binding_address_ip_family=\"inet\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}