name: Infrastructure Tests

on:
  push:
    branches: [main, develop]
    paths:
      - "infrastructure/**"
      - "application/**"
      - "scripts/**"
      - "Makefile"
      - ".github/workflows/infrastructure.yml"
      - "**/*.md"
      - "**/*.yml"
      - "**/*.yaml"
      - "**/*.sh"
  pull_request:
    branches: [main, develop]
    paths:
      - "infrastructure/**"
      - "application/**"
      - "scripts/**"
      - "Makefile"
      - ".github/workflows/infrastructure.yml"
      - "**/*.md"
      - "**/*.yml"
      - "**/*.yaml"
      - "**/*.sh"

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install linting tools
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint shellcheck
          sudo npm install -g markdownlint-cli

      - name: Run linting script
        run: |
          ./scripts/lint.sh
